name: beer_color_converter
description: Dart package that converts SRM beer values to real visible color hexadecimal numbers.
version: 1.0.0
repository: https://github.com/nathanielxd/beer-color-converter

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0